### PR TITLE
This is to fix Issue #8

### PR DESCRIPTION
**Pull request by Soarnsky**
#8

### CODE REVIEW

**Comment by samclane** [comment]
This fixed my issue with `./run.sh`.  I can confirm it works.

**Comment by ricklamers** [comment]
First, thanks for contributing!

Hi Soarnsky - I've updated the run.sh to work on Windows and also now check for an existing docker container image. Could you check if my latest run.sh also works for you? Then I guess that overrides this PR. master @ e9c2f0d.

**Comment by Soarnsky** [comment]
@ricklamers Yep fixed it. Although there still seems to be an issue with the docker

`$ docker logs gridstudio
bash: run-manager-proxy.sh: No such file or directory
bash: run-manager-proxy.sh: No such file or directory
bash: run-manager-proxy.sh: No such file or directory
`

**Comment by Soarnsky** [comment]
Closed because @ricklamers has fixed this on latest

**Comment by ricklamers** [comment]
> @ricklamers Yep fixed it. Although there still seems to be an issue with the docker
> 
> ```
> $ docker logs gridstudio
> bash: run-manager-proxy.sh: No such file or directory
> bash: run-manager-proxy.sh: No such file or directory
> bash: run-manager-proxy.sh: No such file or directory
> ```
> 
> This issue has been created #23

The file seems to be there:
https://github.com/ricklamers/gridstudio/blob/master/grid-app/proxy/run-manager-proxy.sh

Might this be related to the volume not being mounted correctly? I will see if I get the error in the log for a fresh install of the latest master.

**Pull request closed without merging**
